name: flutter_cache_manager
description: Generic cache manager for flutter
version: 0.3.0-alpha.2
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cache_manager

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: "^0.4.0"
  uuid:  "^1.0.3"
  http: ">=0.11.0 < 0.13.0"
  path: "^1.6.2"
  sqflite: "^0.12.2+1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: "^1.3.0"
