name: flutter_cache_manager
description: Generic cache manager for flutter
version: 0.1.0-rc.1
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cache_manager

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: "^0.4.0"
  path_provider: "^0.4.0"
  synchronized: "^1.3.0"
  uuid:  "^0.5.3"
  http: "^0.11.3+14"