name: flutter_cache_manager_firebase
description: CacheManager implementation for firebase_storage. Uses the gs:// as key and translates to https://
version: 2.1.0
homepage: https://github.com/Baseflow/flutter_cache_manager

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.0
  firebase_storage: '>=12.0.0 <13.0.0'
  path_provider: ^2.1.2
  path: ^1.9.0
  retry: ^3.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
