name: flutter_cache_manager_firebase
description: CacheManager implementation for firebase_storage. Uses the gs:// as key and translates to https://
version: 1.1.0-beta
homepage: https://github.com/Baseflow/flutter_cache_manager

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^2.0.0-beta
  firebase_storage: ">=5.0.0 <6.0.0"
  path_provider: "^1.4.0"
  path: "^1.6.4"

dev_dependencies:
  flutter_test:
    sdk: flutter
