name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 3.0.0-nullsafety.3
homepage: https://github.com/Baseflow/flutter_cache_manager

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  clock: ^1.1.0
  collection: ^1.15.0
  file: ^6.1.0
  flutter:
    sdk: flutter
  http: ^0.13.0
  image: ^3.0.1
  path: ^1.8.0
  path_provider: ^2.0.0
  pedantic: ^1.10.0
  rxdart: ^0.26.0
  sqflite: ^2.0.0+3
  uuid: ^3.0.0

dev_dependencies:
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
